/**
 * Gibberish Mode — "Wenomecha" Style Lyrics Transform
 *
 * Converts English (and any Latin-script) lyrics into phonetically-smashed
 * gibberish that looks like how a non-English speaker might transcribe what
 * they hear. Words get dictionary-matched first, then phonetically mangled
 * per-word, then joined together without spaces.
 */

import Defaults from "../../components/Global/Defaults.ts";

// Tracks words that weren't found in the dictionary (fell back to phonetic rules)
const _missedWords: Set<string> = new Set();

/** Clear the missed-words tracker (call before processing a song). */
export function clearMissedWords(): void {
  _missedWords.clear();
}

/** Log all words that weren't in the dictionary (always logs, no DevMode gate). */
export function logMissedWords(): void {
  if (_missedWords.size === 0) return;
  const sorted = [..._missedWords].sort();
  console.log(`[Wenomecha] Words not in dictionary (${sorted.length}): ${sorted.join(", ")}`);
}

// ── Word-level dictionary ─────────────────────────────────────────────────
// Applied BEFORE joining so \b anchors work.
// Organized by category for maintainability.
const WordReplacements: [RegExp, string][] = [
  // ── Contractions ──────────────────────────────────────────────────────
  [/\bi'm\b/gi, "am"],
  [/\bi'll\b/gi, "al"],
  [/\bi've\b/gi, "av"],
  [/\bi'd\b/gi, "ad"],
  [/\byou're\b/gi, "uar"],
  [/\byou'll\b/gi, "ual"],
  [/\byou've\b/gi, "uav"],
  [/\byou'd\b/gi, "uad"],
  [/\bwe're\b/gi, "wiar"],
  [/\bwe'll\b/gi, "wial"],
  [/\bwe've\b/gi, "wiav"],
  [/\bthey're\b/gi, "dear"],
  [/\bthey'll\b/gi, "deal"],
  [/\bthey've\b/gi, "deav"],
  [/\bhe's\b/gi, "his"],
  [/\bshe's\b/gi, "shis"],
  [/\bit's\b/gi, "es"],
  [/\bthat's\b/gi, "das"],
  [/\bwhat's\b/gi, "was"],
  [/\bthere's\b/gi, "ders"],
  [/\bhere's\b/gi, "hias"],
  [/\blet's\b/gi, "les"],
  [/\bdon't\b/gi, "don"],
  [/\bcan't\b/gi, "kan"],
  [/\bwon't\b/gi, "won"],
  [/\bisn't\b/gi, "isen"],
  [/\baren't\b/gi, "aren"],
  [/\bdidn't\b/gi, "diden"],
  [/\bdoesn't\b/gi, "dusen"],
  [/\bwasn't\b/gi, "wosen"],
  [/\bweren't\b/gi, "weren"],
  [/\bwouldn't\b/gi, "wuden"],
  [/\bcouldn't\b/gi, "kuden"],
  [/\bshouldn't\b/gi, "shuden"],
  [/\bhaven't\b/gi, "haven"],
  [/\bhasn't\b/gi, "hasen"],
  [/\bain't\b/gi, "en"],
  // ── Pronouns & Determiners ────────────────────────────────────────────
  [/\bi\b/g, "o"],
  [/\bme\b/gi, "mi"],
  [/\bmy\b/gi, "ma"],
  [/\bmyself\b/gi, "masef"],
  [/\bmine\b/gi, "main"],
  [/\byou\b/gi, "u"],
  [/\byour\b/gi, "ua"],
  [/\byours\b/gi, "uas"],
  [/\byourself\b/gi, "uasef"],
  [/\bwe\b/gi, "wi"],
  [/\bour\b/gi, "awa"],
  [/\bours\b/gi, "awas"],
  [/\bus\b/gi, "as"],
  [/\bhe\b/gi, "hi"],
  [/\bhim\b/gi, "hem"],
  [/\bhis\b/gi, "hes"],
  [/\bhimself\b/gi, "hemsef"],
  [/\bshe\b/gi, "shi"],
  [/\bher\b/gi, "ha"],
  [/\bhers\b/gi, "has"],
  [/\bherself\b/gi, "hasef"],
  [/\bit\b/gi, "et"],
  [/\bits\b/gi, "ets"],
  [/\bitself\b/gi, "etsef"],
  [/\bthey\b/gi, "de"],
  [/\bthem\b/gi, "dem"],
  [/\btheir\b/gi, "da"],
  [/\btheirs\b/gi, "das"],
  [/\bthemselves\b/gi, "demsef"],
  [/\bthe\b/gi, "da"],
  [/\bthis\b/gi, "dis"],
  [/\bthat\b/gi, "da"],
  [/\bthese\b/gi, "dis"],
  [/\bthose\b/gi, "dos"],
  [/\ba\b/gi, "e"],
  [/\ban\b/gi, "en"],

  // ── Common Verbs (be/have/do) ─────────────────────────────────────────
  [/\bis\b/gi, "es"],
  [/\bam\b/gi, "em"],
  [/\bare\b/gi, "ar"],
  [/\bwas\b/gi, "wos"],
  [/\bwere\b/gi, "wer"],
  [/\bbeen\b/gi, "bin"],
  [/\bbeing\b/gi, "bin"],
  [/\bbe\b/gi, "bi"],
  [/\bhave\b/gi, "haf"],
  [/\bhas\b/gi, "hes"],
  [/\bhad\b/gi, "hed"],
  [/\bhaving\b/gi, "hafin"],
  [/\bdo\b/gi, "du"],
  [/\bdoes\b/gi, "das"],
  [/\bdid\b/gi, "ded"],
  [/\bdoing\b/gi, "duin"],
  [/\bdone\b/gi, "dan"],

  // ── Modal / Auxiliary Verbs ───────────────────────────────────────────
  [/\bwill\b/gi, "wil"],
  [/\bwould\b/gi, "wud"],
  [/\bshall\b/gi, "shal"],
  [/\bshould\b/gi, "shud"],
  [/\bcan\b/gi, "ken"],
  [/\bcould\b/gi, "kul"],
  [/\bmay\b/gi, "me"],
  [/\bmight\b/gi, "mai"],
  [/\bmust\b/gi, "mas"],
  [/\bneed\b/gi, "nid"],
  [/\bwant\b/gi, "wan"],
  [/\bwanted\b/gi, "waned"],
  [/\bwanting\b/gi, "wanin"],

  // ── Common Action Verbs ───────────────────────────────────────────────
  [/\bgo\b/gi, "gu"],
  [/\bgoes\b/gi, "gos"],
  [/\bgoing\b/gi, "goin"],
  [/\bgone\b/gi, "gon"],
  [/\bwent\b/gi, "wen"],
  [/\bget\b/gi, "ge"],
  [/\bgets\b/gi, "ges"],
  [/\bgetting\b/gi, "getin"],
  [/\bgot\b/gi, "go"],
  [/\bgotten\b/gi, "gotn"],
  [/\bcome\b/gi, "kam"],
  [/\bcomes\b/gi, "kams"],
  [/\bcoming\b/gi, "kamin"],
  [/\bcame\b/gi, "kem"],
  [/\bmake\b/gi, "mek"],
  [/\bmakes\b/gi, "meks"],
  [/\bmaking\b/gi, "mekin"],
  [/\bmade\b/gi, "med"],
  [/\btake\b/gi, "tek"],
  [/\btakes\b/gi, "teks"],
  [/\btaking\b/gi, "tekin"],
  [/\btook\b/gi, "tuk"],
  [/\btaken\b/gi, "tekn"],
  [/\bgive\b/gi, "gif"],
  [/\bgives\b/gi, "gifs"],
  [/\bgiving\b/gi, "gifin"],
  [/\bgave\b/gi, "gef"],
  [/\bgiven\b/gi, "gifn"],
  [/\bput\b/gi, "pu"],
  [/\bputs\b/gi, "pus"],
  [/\bputting\b/gi, "puin"],
  [/\blet\b/gi, "le"],
  [/\blets\b/gi, "les"],
  [/\bletting\b/gi, "lein"],
  [/\bkeep\b/gi, "kip"],
  [/\bkeeps\b/gi, "kips"],
  [/\bkeeping\b/gi, "kipin"],
  [/\bkept\b/gi, "kep"],
  [/\btry\b/gi, "tra"],
  [/\btries\b/gi, "tras"],
  [/\btrying\b/gi, "train"],
  [/\btried\b/gi, "trad"],
  [/\brun\b/gi, "ran"],
  [/\bruns\b/gi, "rans"],
  [/\brunning\b/gi, "ranin"],
  [/\bran\b/gi, "ren"],
  [/\bturn\b/gi, "ter"],
  [/\bturns\b/gi, "ters"],
  [/\bturning\b/gi, "terin"],
  [/\bturned\b/gi, "terd"],
  [/\bfall\b/gi, "fol"],
  [/\bfalls\b/gi, "fols"],
  [/\bfalling\b/gi, "folin"],
  [/\bfell\b/gi, "fel"],
  [/\bfallen\b/gi, "foln"],
  [/\bhold\b/gi, "hol"],
  [/\bholds\b/gi, "hols"],
  [/\bholding\b/gi, "holin"],
  [/\bheld\b/gi, "hel"],
  [/\bwait\b/gi, "wet"],
  [/\bwaits\b/gi, "wets"],
  [/\bwaiting\b/gi, "wetin"],
  [/\bstop\b/gi, "sto"],
  [/\bstops\b/gi, "stos"],
  [/\bstopping\b/gi, "stoin"],
  [/\bstopped\b/gi, "stod"],
  [/\bstart\b/gi, "star"],
  [/\bstarts\b/gi, "stars"],
  [/\bstarting\b/gi, "starin"],
  [/\bstarted\b/gi, "stard"],
  [/\bend\b/gi, "en"],
  [/\bends\b/gi, "ens"],
  [/\bending\b/gi, "enin"],
  [/\bended\b/gi, "end"],
  [/\bshow\b/gi, "sho"],
  [/\bshows\b/gi, "shos"],
  [/\bshowing\b/gi, "shoin"],
  [/\bshowed\b/gi, "shod"],
  [/\bshown\b/gi, "shon"],
  [/\bask\b/gi, "as"],
  [/\basks\b/gi, "ass"],
  [/\basking\b/gi, "asin"],
  [/\basked\b/gi, "asd"],
  [/\buse\b/gi, "yus"],
  [/\buses\b/gi, "yuses"],
  [/\busing\b/gi, "yusin"],
  [/\bused\b/gi, "yusd"],
  [/\bset\b/gi, "se"],
  [/\bsets\b/gi, "ses"],
  [/\bsetting\b/gi, "sein"],
  [/\bact\b/gi, "ak"],
  [/\bacts\b/gi, "aks"],
  [/\bacting\b/gi, "akin"],
  [/\blay\b/gi, "le"],
  [/\blays\b/gi, "les"],
  [/\blaying\b/gi, "lein"],
  [/\blaid\b/gi, "led"],
  [/\blie\b/gi, "la"],
  [/\blies\b/gi, "las"],
  [/\blying\b/gi, "lain"],
  [/\blied\b/gi, "laid"],
  [/\bmet\b/gi, "me"],

  // ── Perception / Communication Verbs ──────────────────────────────────
  [/\bsee\b/gi, "si"],
  [/\bsees\b/gi, "sis"],
  [/\bseeing\b/gi, "siin"],
  [/\bsaw\b/gi, "so"],
  [/\bseen\b/gi, "sin"],
  [/\blook\b/gi, "luk"],
  [/\blooks\b/gi, "luks"],
  [/\blooking\b/gi, "lukin"],
  [/\blooked\b/gi, "lukd"],
  [/\bwatch\b/gi, "woch"],
  [/\bwatching\b/gi, "wochin"],
  [/\bhear\b/gi, "hia"],
  [/\bhears\b/gi, "hias"],
  [/\bhearing\b/gi, "hiain"],
  [/\bheard\b/gi, "hiad"],
  [/\blisten\b/gi, "lisn"],
  [/\blistening\b/gi, "lisnin"],
  [/\btell\b/gi, "tel"],
  [/\btells\b/gi, "tels"],
  [/\btelling\b/gi, "telin"],
  [/\btold\b/gi, "tol"],
  [/\bsay\b/gi, "se"],
  [/\bsays\b/gi, "ses"],
  [/\bsaying\b/gi, "sein"],
  [/\bsaid\b/gi, "sed"],
  [/\bspeak\b/gi, "spik"],
  [/\bspeaking\b/gi, "spikin"],
  [/\bspoke\b/gi, "spok"],
  [/\bspoken\b/gi, "spokn"],
  [/\btalk\b/gi, "tok"],
  [/\btalks\b/gi, "toks"],
  [/\btalking\b/gi, "tokin"],
  [/\bcall\b/gi, "kol"],
  [/\bcalls\b/gi, "kols"],
  [/\bcalling\b/gi, "kolin"],
  [/\bcalled\b/gi, "kold"],
  [/\bthink\b/gi, "tink"],
  [/\bthinks\b/gi, "tinks"],
  [/\bthinking\b/gi, "tinkin"],
  [/\bthought\b/gi, "tot"],
  [/\bknow\b/gi, "no"],
  [/\bknows\b/gi, "nos"],
  [/\bknowing\b/gi, "noin"],
  [/\bknew\b/gi, "nu"],
  [/\bknown\b/gi, "non"],
  [/\bfeel\b/gi, "fil"],
  [/\bfeels\b/gi, "fils"],
  [/\bfeeling\b/gi, "filin"],
  [/\bfelt\b/gi, "fel"],
  [/\bbelieve\b/gi, "bilif"],
  [/\bbelieving\b/gi, "bilifin"],
  [/\bbelieved\b/gi, "bilifd"],
  [/\bunderstand\b/gi, "andastan"],
  [/\bremember\b/gi, "rimemba"],
  [/\bforget\b/gi, "foge"],
  [/\bforgot\b/gi, "fogo"],
  [/\bforgotten\b/gi, "fogotn"],

  // ── Motion / Position Verbs ───────────────────────────────────────────
  [/\bmove\b/gi, "muf"],
  [/\bmoves\b/gi, "mufs"],
  [/\bmoving\b/gi, "mufin"],
  [/\bmoved\b/gi, "mufd"],
  [/\bwalk\b/gi, "wok"],
  [/\bwalks\b/gi, "woks"],
  [/\bwalking\b/gi, "wokin"],
  [/\bstand\b/gi, "stan"],
  [/\bstanding\b/gi, "stanin"],
  [/\bstood\b/gi, "stud"],
  [/\bsit\b/gi, "se"],
  [/\bsitting\b/gi, "sein"],
  [/\bsat\b/gi, "sa"],
  [/\brise\b/gi, "rais"],
  [/\brising\b/gi, "raisin"],
  [/\brose\b/gi, "ros"],
  [/\brisen\b/gi, "risn"],
  [/\bfly\b/gi, "fla"],
  [/\bflying\b/gi, "flain"],
  [/\bflew\b/gi, "flu"],
  [/\bdrive\b/gi, "draif"],
  [/\bdriving\b/gi, "draifin"],
  [/\bdrove\b/gi, "drof"],
  [/\breach\b/gi, "rich"],
  [/\breaching\b/gi, "richin"],
  [/\breached\b/gi, "richd"],
  [/\bleave\b/gi, "lif"],
  [/\bleaving\b/gi, "lifin"],
  [/\bleft\b/gi, "lef"],
  [/\bstay\b/gi, "ste"],
  [/\bstays\b/gi, "stes"],
  [/\bstaying\b/gi, "stein"],
  [/\bstayed\b/gi, "sted"],
  [/\bfollow\b/gi, "folo"],
  [/\bfollowing\b/gi, "foloin"],
  [/\bfollowed\b/gi, "folod"],
  [/\blead\b/gi, "lid"],
  [/\bleading\b/gi, "lidin"],
  [/\bled\b/gi, "lad"],
  [/\bpull\b/gi, "pul"],
  [/\bpulling\b/gi, "pulin"],
  [/\bpush\b/gi, "pus"],
  [/\bpushing\b/gi, "pushin"],
  [/\bcarry\b/gi, "kari"],
  [/\bcarrying\b/gi, "kariin"],
  [/\bcarried\b/gi, "karid"],
  [/\bbring\b/gi, "brin"],
  [/\bbringing\b/gi, "brinin"],
  [/\bbrought\b/gi, "brot"],
  [/\bsend\b/gi, "sen"],
  [/\bsending\b/gi, "senin"],
  [/\bsent\b/gi, "sen"],

  // ── Emotional / State Verbs ───────────────────────────────────────────
  [/\blove\b/gi, "luf"],
  [/\bloves\b/gi, "lufs"],
  [/\bloving\b/gi, "lufin"],
  [/\bloved\b/gi, "lufd"],
  [/\bhate\b/gi, "het"],
  [/\bhates\b/gi, "hets"],
  [/\bhating\b/gi, "hetin"],
  [/\bhated\b/gi, "hetd"],
  [/\blike\b/gi, "laik"],
  [/\blikes\b/gi, "laiks"],
  [/\bliking\b/gi, "laikin"],
  [/\bliked\b/gi, "laikd"],
  [/\bmiss\b/gi, "mis"],
  [/\bmisses\b/gi, "mises"],
  [/\bmissing\b/gi, "misin"],
  [/\bmissed\b/gi, "misd"],
  [/\bwish\b/gi, "wis"],
  [/\bwishes\b/gi, "wishs"],
  [/\bwishing\b/gi, "wishin"],
  [/\bhope\b/gi, "hop"],
  [/\bhopes\b/gi, "hops"],
  [/\bhoping\b/gi, "hopin"],
  [/\bhoped\b/gi, "hopd"],
  [/\bdream\b/gi, "drim"],
  [/\bdreams\b/gi, "drims"],
  [/\bdreaming\b/gi, "drimin"],
  [/\bcry\b/gi, "kra"],
  [/\bcries\b/gi, "kras"],
  [/\bcrying\b/gi, "krain"],
  [/\bcried\b/gi, "krad"],
  [/\blaugh\b/gi, "laf"],
  [/\blaughing\b/gi, "lafin"],
  [/\blaughed\b/gi, "lafd"],
  [/\bsmile\b/gi, "smail"],
  [/\bsmiling\b/gi, "smailin"],
  [/\bsmiled\b/gi, "smaild"],
  [/\bsing\b/gi, "sin"],
  [/\bsings\b/gi, "sins"],
  [/\bsinging\b/gi, "sinin"],
  [/\bsang\b/gi, "san"],
  [/\bsung\b/gi, "san"],
  [/\bdance\b/gi, "dans"],
  [/\bdances\b/gi, "danses"],
  [/\bdancing\b/gi, "dansin"],
  [/\bdanced\b/gi, "dansd"],
  [/\bplay\b/gi, "ple"],
  [/\bplays\b/gi, "ples"],
  [/\bplaying\b/gi, "plein"],
  [/\bplayed\b/gi, "pled"],
  [/\bfight\b/gi, "fai"],
  [/\bfighting\b/gi, "faiin"],
  [/\bfought\b/gi, "fot"],
  [/\bkill\b/gi, "kil"],
  [/\bkilling\b/gi, "kilin"],
  [/\bkilled\b/gi, "kild"],
  [/\bdie\b/gi, "dai"],
  [/\bdies\b/gi, "dais"],
  [/\bdying\b/gi, "dain"],
  [/\bdied\b/gi, "daid"],
  [/\bdead\b/gi, "ded"],
  [/\blive\b/gi, "lif"],
  [/\blives\b/gi, "lifs"],
  [/\bliving\b/gi, "lifin"],
  [/\balive\b/gi, "alaif"],
  [/\bburn\b/gi, "bern"],
  [/\bburning\b/gi, "bernin"],
  [/\bburned\b/gi, "bernd"],
  [/\bburnt\b/gi, "bern"],
  [/\bshine\b/gi, "shain"],
  [/\bshining\b/gi, "shainin"],
  [/\bbreak\b/gi, "brek"],
  [/\bbreaking\b/gi, "brekin"],
  [/\bbroke\b/gi, "brok"],
  [/\bbroken\b/gi, "brokn"],
  [/\bfix\b/gi, "fiks"],
  [/\bfixing\b/gi, "fiksin"],
  [/\bfixed\b/gi, "fiksd"],
  [/\bbuild\b/gi, "bil"],
  [/\bbuilding\b/gi, "bilin"],
  [/\bbuilt\b/gi, "bil"],
  [/\bcreate\b/gi, "krie"],
  [/\bcreating\b/gi, "kriein"],
  [/\bdestroy\b/gi, "distro"],
  [/\bdestroying\b/gi, "distroin"],
  [/\bdestroyed\b/gi, "distrod"],
  [/\bopen\b/gi, "opn"],
  [/\bopening\b/gi, "opnin"],
  [/\bopened\b/gi, "opnd"],
  [/\bclose\b/gi, "klos"],
  [/\bclosing\b/gi, "klosin"],
  [/\bclosed\b/gi, "klosd"],
  [/\bfind\b/gi, "faind"],
  [/\bfinds\b/gi, "fainds"],
  [/\bfinding\b/gi, "faindin"],
  [/\bfound\b/gi, "faun"],
  [/\blose\b/gi, "lus"],
  [/\blosing\b/gi, "lusin"],
  [/\blost\b/gi, "los"],
  [/\bchoose\b/gi, "chus"],
  [/\bchoosing\b/gi, "chusin"],
  [/\bchose\b/gi, "chos"],
  [/\bchosen\b/gi, "chosn"],
  [/\bchange\b/gi, "chen"],
  [/\bchanging\b/gi, "chenin"],
  [/\bchanged\b/gi, "chend"],
  [/\bgrow\b/gi, "gro"],
  [/\bgrowing\b/gi, "groin"],
  [/\bgrew\b/gi, "gru"],
  [/\bgrown\b/gi, "gron"],
  [/\blearn\b/gi, "lern"],
  [/\blearning\b/gi, "lernin"],
  [/\blearned\b/gi, "lernd"],
  [/\bteach\b/gi, "tich"],
  [/\bteaching\b/gi, "tichin"],
  [/\btaught\b/gi, "tot"],
  [/\bread\b/gi, "rid"],
  [/\breading\b/gi, "ridin"],
  [/\bwrite\b/gi, "rai"],
  [/\bwriting\b/gi, "rain"],
  [/\bwrote\b/gi, "rot"],
  [/\bwritten\b/gi, "ritn"],
  [/\bdraw\b/gi, "dro"],
  [/\bdrawing\b/gi, "droin"],
  [/\bdrew\b/gi, "dru"],
  [/\bdrawn\b/gi, "dron"],
  [/\bpay\b/gi, "pe"],
  [/\bpaying\b/gi, "pein"],
  [/\bpaid\b/gi, "ped"],
  [/\bbuy\b/gi, "ba"],
  [/\bbuying\b/gi, "bain"],
  [/\bbought\b/gi, "bot"],
  [/\bsell\b/gi, "sel"],
  [/\bselling\b/gi, "selin"],
  [/\bsold\b/gi, "sol"],
  [/\bsleep\b/gi, "slip"],
  [/\bsleeping\b/gi, "slipin"],
  [/\bslept\b/gi, "slep"],
  [/\bwake\b/gi, "wek"],
  [/\bwaking\b/gi, "wekin"],
  [/\bwoke\b/gi, "wok"],
  [/\bwoken\b/gi, "wokn"],
  [/\beat\b/gi, "it"],
  [/\beating\b/gi, "itin"],
  [/\bate\b/gi, "et"],
  [/\beaten\b/gi, "itn"],
  [/\bdrink\b/gi, "drin"],
  [/\bdrinking\b/gi, "drinin"],
  [/\bdrank\b/gi, "dran"],
  [/\bdrunk\b/gi, "dran"],
  [/\bhit\b/gi, "he"],
  [/\bhitting\b/gi, "hein"],
  [/\bcut\b/gi, "ka"],
  [/\bcutting\b/gi, "kain"],
  [/\bpick\b/gi, "pik"],
  [/\bpicking\b/gi, "pikin"],
  [/\bpicked\b/gi, "pikd"],
  [/\bwear\b/gi, "wea"],
  [/\bwearing\b/gi, "weain"],
  [/\bwore\b/gi, "wor"],
  [/\bworn\b/gi, "won"],
  [/\bhelp\b/gi, "hel"],
  [/\bhelps\b/gi, "hels"],
  [/\bhelping\b/gi, "helin"],
  [/\bhelped\b/gi, "held"],
  [/\bwork\b/gi, "wok"],
  [/\bworks\b/gi, "woks"],
  [/\bworking\b/gi, "wokin"],
  [/\bworked\b/gi, "wokd"],
  [/\bsave\b/gi, "sef"],
  [/\bsaving\b/gi, "sefin"],
  [/\bsaved\b/gi, "sefd"],
  [/\bwanna\b/gi, "wana"],
  [/\bgonna\b/gi, "gona"],
  [/\bgotta\b/gi, "gota"],

  // ── Prepositions / Conjunctions / Particles ───────────────────────────
  [/\bin\b/gi, "en"],
  [/\binto\b/gi, "intu"],
  [/\bon\b/gi, "un"],
  [/\bat\b/gi, "a"],
  [/\bto\b/gi, "tu"],
  [/\bfor\b/gi, "fo"],
  [/\bfrom\b/gi, "fro"],
  [/\bof\b/gi, "ov"],
  [/\bwith\b/gi, "wit"],
  [/\bwithout\b/gi, "witau"],
  [/\bby\b/gi, "ba"],
  [/\bup\b/gi, "ap"],
  [/\bout\b/gi, "au"],
  [/\boff\b/gi, "of"],
  [/\bdown\b/gi, "daun"],
  [/\bover\b/gi, "ova"],
  [/\bunder\b/gi, "anda"],
  [/\babove\b/gi, "abuf"],
  [/\bbelow\b/gi, "bilo"],
  [/\bbetween\b/gi, "bitwin"],
  [/\bbehind\b/gi, "bihaind"],
  [/\bbefore\b/gi, "bifo"],
  [/\bafter\b/gi, "afta"],
  [/\babout\b/gi, "abau"],
  [/\baround\b/gi, "araun"],
  [/\bthrough\b/gi, "tru"],
  [/\bthough\b/gi, "do"],
  [/\balthough\b/gi, "oldo"],
  [/\bacross\b/gi, "akros"],
  [/\balong\b/gi, "alon"],
  [/\bagainst\b/gi, "agen"],
  [/\btoward\b/gi, "tuward"],
  [/\btowards\b/gi, "tuwards"],
  [/\band\b/gi, "an"],
  [/\bbut\b/gi, "bu"],
  [/\bor\b/gi, "o"],
  [/\bif\b/gi, "ef"],
  [/\bso\b/gi, "su"],
  [/\bbecause\b/gi, "bikos"],
  [/\bsince\b/gi, "sins"],
  [/\buntil\b/gi, "antil"],
  [/\bwhile\b/gi, "wail"],
  [/\bwhen\b/gi, "wen"],
  [/\bwhere\b/gi, "wea"],
  [/\bwhat\b/gi, "wa"],
  [/\bwhich\b/gi, "wich"],
  [/\bwho\b/gi, "hu"],
  [/\bhow\b/gi, "hau"],
  [/\bwhy\b/gi, "wai"],
  [/\bthen\b/gi, "den"],
  [/\bthan\b/gi, "dan"],

  // ── Adjectives / Adverbs ──────────────────────────────────────────────
  [/\bgood\b/gi, "gu"],
  [/\bbetter\b/gi, "beta"],
  [/\bbest\b/gi, "bes"],
  [/\bbad\b/gi, "ba"],
  [/\bworse\b/gi, "wos"],
  [/\bworst\b/gi, "wos"],
  [/\bnew\b/gi, "nyu"],
  [/\bold\b/gi, "ol"],
  [/\bbig\b/gi, "bi"],
  [/\bsmall\b/gi, "smol"],
  [/\btall\b/gi, "tol"],
  [/\bshort\b/gi, "shor"],
  [/\blong\b/gi, "lon"],
  [/\blonger\b/gi, "longa"],
  [/\blongest\b/gi, "longes"],
  [/\bhigh\b/gi, "hai"],
  [/\bhigher\b/gi, "haia"],
  [/\bhighest\b/gi, "haies"],
  [/\blow\b/gi, "lo"],
  [/\blower\b/gi, "loa"],
  [/\bfast\b/gi, "fas"],
  [/\bslow\b/gi, "slo"],
  [/\bhard\b/gi, "ha"],
  [/\bsoft\b/gi, "sof"],
  [/\bloud\b/gi, "lau"],
  [/\bquiet\b/gi, "kwaie"],
  [/\bhot\b/gi, "ho"],
  [/\bcold\b/gi, "kol"],
  [/\bwarm\b/gi, "wom"],
  [/\bcool\b/gi, "kul"],
  [/\breal\b/gi, "ril"],
  [/\breally\b/gi, "rili"],
  [/\btrue\b/gi, "tru"],
  [/\btruly\b/gi, "truli"],
  [/\bfull\b/gi, "ful"],
  [/\bempty\b/gi, "emti"],
  [/\brich\b/gi, "ric"],
  [/\bpoor\b/gi, "pua"],
  [/\bstrong\b/gi, "stron"],
  [/\bweak\b/gi, "wik"],
  [/\bhappy\b/gi, "hapi"],
  [/\bsad\b/gi, "sed"],
  [/\bangry\b/gi, "angri"],
  [/\bscary\b/gi, "skeri"],
  [/\bcrazy\b/gi, "kresi"],
  [/\bsafe\b/gi, "sef"],
  [/\bdangerous\b/gi, "denjrus"],
  [/\bbeautiful\b/gi, "byutifo"],
  [/\bugly\b/gi, "ugli"],
  [/\bpretty\b/gi, "priti"],
  [/\bhandsome\b/gi, "hansam"],
  [/\bperfect\b/gi, "perfek"],
  [/\bwrong\b/gi, "ron"],
  [/\bright\b/gi, "rai"],
  [/\bready\b/gi, "redi"],
  [/\bfree\b/gi, "fri"],
  [/\bbusy\b/gi, "bisi"],
  [/\beasy\b/gi, "isi"],
  [/\bdifficult\b/gi, "difikol"],
  [/\bsimple\b/gi, "simpo"],
  [/\bspecial\b/gi, "spesho"],
  [/\bimportant\b/gi, "impotan"],
  [/\bdifferent\b/gi, "difren"],
  [/\bsame\b/gi, "sem"],
  [/\bother\b/gi, "ada"],
  [/\bnext\b/gi, "nek"],
  [/\blast\b/gi, "las"],
  [/\bfirst\b/gi, "fers"],
  [/\bsecond\b/gi, "sekon"],
  [/\bonly\b/gi, "onli"],
  [/\bown\b/gi, "on"],
  [/\bevery\b/gi, "evri"],
  [/\beach\b/gi, "ich"],
  [/\bboth\b/gi, "bot"],
  [/\ball\b/gi, "ol"],
  [/\bmany\b/gi, "meni"],
  [/\bmuch\b/gi, "mach"],
  [/\bmore\b/gi, "mo"],
  [/\bmost\b/gi, "mos"],
  [/\bless\b/gi, "les"],
  [/\bleast\b/gi, "lis"],
  [/\bfew\b/gi, "fu"],
  [/\benough\b/gi, "enaf"],
  [/\blate\b/gi, "let"],
  [/\bearly\b/gi, "erli"],
  [/\bsoon\b/gi, "sun"],
  [/\bnow\b/gi, "nau"],
  [/\bthen\b/gi, "den"],
  [/\bstill\b/gi, "stil"],
  [/\balso\b/gi, "olso"],
  [/\beven\b/gi, "ifn"],
  [/\btoo\b/gi, "tu"],
  [/\bvery\b/gi, "veri"],
  [/\bjust\b/gi, "jas"],
  [/\bback\b/gi, "bak"],
  [/\bhere\b/gi, "hia"],
  [/\bthere\b/gi, "dea"],
  [/\beverywhere\b/gi, "evriwea"],
  [/\bnowhere\b/gi, "nowea"],
  [/\bsomewhere\b/gi, "samwea"],
  [/\banywhere\b/gi, "eniwea"],
  [/\balways\b/gi, "olwes"],
  [/\bnever\b/gi, "neva"],
  [/\bsometimes\b/gi, "samtaims"],
  [/\bmaybe\b/gi, "mebi"],
  [/\bprobably\b/gi, "probli"],
  [/\bactually\b/gi, "akchuli"],
  [/\bbasically\b/gi, "besikli"],
  [/\bliterally\b/gi, "litrali"],
  [/\bfinally\b/gi, "fainali"],
  [/\balready\b/gi, "olredi"],
  [/\btogether\b/gi, "tuget"],
  [/\bapart\b/gi, "apa"],
  [/\baway\b/gi, "awe"],
  [/\binside\b/gi, "insaid"],
  [/\boutside\b/gi, "autsaid"],
  [/\bagain\b/gi, "agen"],
  [/\bforever\b/gi, "foreva"],
  [/\binnocent\b/gi, "inoce"],

  // ── Nouns (People / Body / Nature / Objects) ──────────────────────────
  [/\bpeople\b/gi, "pipl"],
  [/\bperson\b/gi, "persn"],
  [/\bman\b/gi, "men"],
  [/\bwoman\b/gi, "wumen"],
  [/\bboy\b/gi, "bo"],
  [/\bgirl\b/gi, "gal"],
  [/\bchild\b/gi, "chaild"],
  [/\bchildren\b/gi, "childrin"],
  [/\bbaby\b/gi, "beby"],
  [/\bfriend\b/gi, "fren"],
  [/\bfriends\b/gi, "frens"],
  [/\bbrother\b/gi, "brada"],
  [/\bsister\b/gi, "sista"],
  [/\bmother\b/gi, "mada"],
  [/\bfather\b/gi, "fada"],
  [/\bfamily\b/gi, "famili"],
  [/\bheart\b/gi, "har"],
  [/\bheartbeat\b/gi, "jarbi"],
  [/\bhearts\b/gi, "hars"],
  [/\bmind\b/gi, "maind"],
  [/\bsoul\b/gi, "sol"],
  [/\bbody\b/gi, "badi"],
  [/\bhand\b/gi, "han"],
  [/\bhands\b/gi, "hans"],
  [/\bhead\b/gi, "hed"],
  [/\bface\b/gi, "fes"],
  [/\beyes\b/gi, "ais"],
  [/\beye\b/gi, "ai"],
  [/\blips\b/gi, "leps"],
  [/\bmouth\b/gi, "mau"],
  [/\barms\b/gi, "ams"],
  [/\barm\b/gi, "am"],
  [/\bblood\b/gi, "blad"],
  [/\btears\b/gi, "tias"],
  [/\btear\b/gi, "tia"],
  [/\bvoice\b/gi, "voys"],
  [/\bbreath\b/gi, "bref"],
  [/\bskin\b/gi, "sken"],
  [/\bbone\b/gi, "bon"],
  [/\bbones\b/gi, "bons"],
  [/\bworld\b/gi, "wald"],
  [/\bearth\b/gi, "ert"],
  [/\bsky\b/gi, "ska"],
  [/\bskies\b/gi, "skys"],
  [/\bsun\b/gi, "san"],
  [/\bmoon\b/gi, "mun"],
  [/\bstar\b/gi, "sta"],
  [/\bstars\b/gi, "stas"],
  [/\blight\b/gi, "lai"],
  [/\blights\b/gi, "lais"],
  [/\bdark\b/gi, "dak"],
  [/\bdarkness\b/gi, "daknes"],
  [/\bshadow\b/gi, "shado"],
  [/\bshadows\b/gi, "shados"],
  [/\bfire\b/gi, "faia"],
  [/\bflame\b/gi, "flem"],
  [/\bflames\b/gi, "flems"],
  [/\bwater\b/gi, "wata"],
  [/\brain\b/gi, "ren"],
  [/\bwind\b/gi, "win"],
  [/\bstorm\b/gi, "stom"],
  [/\bsnow\b/gi, "sno"],
  [/\bice\b/gi, "ais"],
  [/\bocean\b/gi, "oshun"],
  [/\bsea\b/gi, "si"],
  [/\bwave\b/gi, "wef"],
  [/\bwaves\b/gi, "wefs"],
  [/\briver\b/gi, "riva"],
  [/\bmountain\b/gi, "mauntn"],
  [/\bground\b/gi, "graun"],
  [/\bfloor\b/gi, "flo"],
  [/\btree\b/gi, "tri"],
  [/\btrees\b/gi, "tris"],
  [/\bflower\b/gi, "flawa"],
  [/\bflowers\b/gi, "flawas"],
  [/\bleaf\b/gi, "lif"],
  [/\bleaves\b/gi, "lifs"],
  [/\brose\b/gi, "ros"],
  [/\bgarden\b/gi, "gadn"],
  [/\bfield\b/gi, "fild"],
  [/\bforest\b/gi, "fores"],
  [/\bnight\b/gi, "nai"],
  [/\bnights\b/gi, "nais"],
  [/\bday\b/gi, "de"],
  [/\bdays\b/gi, "des"],
  [/\bmorning\b/gi, "monin"],
  [/\bevening\b/gi, "ifnin"],
  [/\btonight\b/gi, "tunai"],
  [/\btoday\b/gi, "tude"],
  [/\btomorrow\b/gi, "tumoro"],
  [/\byesterday\b/gi, "yestade"],
  [/\btime\b/gi, "taim"],
  [/\btimes\b/gi, "taims"],
  [/\bmoment\b/gi, "momen"],
  [/\bsecond\b/gi, "sekon"],
  [/\bminute\b/gi, "minu"],
  [/\bhour\b/gi, "awa"],
  [/\byear\b/gi, "yia"],
  [/\byears\b/gi, "yias"],
  [/\blife\b/gi, "laif"],
  [/\blives\b/gi, "laifs"],
  [/\bdeath\b/gi, "def"],
  [/\bpower\b/gi, "pawa"],
  [/\benergy\b/gi, "eneji"],
  [/\bpeace\b/gi, "pis"],
  [/\bwar\b/gi, "wo"],
  [/\bpain\b/gi, "pen"],
  [/\bjoy\b/gi, "jo"],
  [/\bhappiness\b/gi, "hapines"],
  [/\banger\b/gi, "anga"],
  [/\bfear\b/gi, "fia"],
  [/\bhope\b/gi, "hop"],
  [/\btruth\b/gi, "trut"],
  [/\bfreedom\b/gi, "fridom"],
  [/\bdream\b/gi, "drim"],
  [/\bdreams\b/gi, "drims"],
  [/\bdesire\b/gi, "disaia"],
  [/\bfaith\b/gi, "feit"],
  [/\btrust\b/gi, "tras"],
  [/\bpromise\b/gi, "promis"],
  [/\bsecret\b/gi, "sikre"],
  [/\bstory\b/gi, "stori"],
  [/\bstories\b/gi, "storis"],
  [/\bsong\b/gi, "son"],
  [/\bsongs\b/gi, "sons"],
  [/\bmusic\b/gi, "myuzik"],
  [/\bword\b/gi, "wod"],
  [/\bwords\b/gi, "wods"],
  [/\bname\b/gi, "nem"],
  [/\bnames\b/gi, "nems"],
  [/\bplace\b/gi, "ples"],
  [/\bplaces\b/gi, "pleses"],
  [/\broom\b/gi, "rum"],
  [/\bhouse\b/gi, "haus"],
  [/\bhome\b/gi, "hom"],
  [/\bdoor\b/gi, "do"],
  [/\bwindow\b/gi, "windo"],
  [/\bwall\b/gi, "wol"],
  [/\bwalls\b/gi, "wols"],
  [/\broad\b/gi, "rod"],
  [/\bstreet\b/gi, "strit"],
  [/\bcity\b/gi, "siti"],
  [/\bcountry\b/gi, "kantri"],
  [/\bside\b/gi, "said"],
  [/\bpart\b/gi, "pa"],
  [/\bway\b/gi, "we"],
  [/\bways\b/gi, "wes"],
  [/\bthing\b/gi, "tin"],
  [/\bthings\b/gi, "tins"],
  [/\beverything\b/gi, "evrtin"],
  [/\bsomething\b/gi, "samtin"],
  [/\bnothing\b/gi, "natin"],
  [/\banything\b/gi, "enitin"],
  [/\beveryone\b/gi, "evrwan"],
  [/\bsomeone\b/gi, "samwan"],
  [/\banyone\b/gi, "eniwan"],
  [/\bnobody\b/gi, "nobadi"],
  [/\beverybody\b/gi, "evribadi"],
  [/\bsomebody\b/gi, "sambadi"],
  [/\bmoney\b/gi, "mani"],
  [/\bletter\b/gi, "leta"],
  [/\bphone\b/gi, "fon"],
  [/\bking\b/gi, "kin"],
  [/\bqueen\b/gi, "kwin"],
  [/\bprince\b/gi, "prins"],
  [/\bprincess\b/gi, "prinses"],
  [/\bhero\b/gi, "hiro"],
  [/\bangel\b/gi, "enjl"],
  [/\bdevil\b/gi, "defl"],
  [/\bgod\b/gi, "gad"],
  [/\bheaven\b/gi, "hefn"],
  [/\bhell\b/gi, "hel"],
  [/\bchurch\b/gi, "cherch"],
  [/\bdrug\b/gi, "drag"],
  [/\bdrugs\b/gi, "drags"],
  [/\bgun\b/gi, "gan"],
  [/\bguns\b/gi, "gans"],
  [/\bcar\b/gi, "ka"],
  [/\bclothes\b/gi, "klos"],
  [/\bshoes\b/gi, "shus"],
  [/\bring\b/gi, "rin"],
  [/\bchain\b/gi, "chen"],
  [/\bgold\b/gi, "gol"],
  [/\bdiamonds\b/gi, "daimns"],
  [/\bdiamond\b/gi, "daimn"],
  [/\bcrown\b/gi, "kraun"],
  [/\bthrone\b/gi, "tron"],

  // ── Colours ───────────────────────────────────────────────────────────
  [/\bblack\b/gi, "blak"],
  [/\bwhite\b/gi, "wai"],
  [/\bred\b/gi, "rad"],
  [/\bblue\b/gi, "blu"],
  [/\bgreen\b/gi, "grin"],
  [/\byellow\b/gi, "yelo"],
  [/\bgolden\b/gi, "goldn"],
  [/\bbrown\b/gi, "braun"],
  [/\bpurple\b/gi, "perpo"],
  [/\bpink\b/gi, "penk"],
  [/\bgrey\b/gi, "gre"],
  [/\bgray\b/gi, "gre"],

  // ── Numbers / Quantity Words ──────────────────────────────────────────
  [/\bone\b/gi, "wan"],
  [/\btwo\b/gi, "tu"],
  [/\bthree\b/gi, "tri"],
  [/\bfour\b/gi, "fo"],
  [/\bfive\b/gi, "faif"],
  [/\bsix\b/gi, "siks"],
  [/\bseven\b/gi, "sefn"],
  [/\beight\b/gi, "et"],
  [/\bnine\b/gi, "nain"],
  [/\bten\b/gi, "tan"],
  [/\bhundred\b/gi, "handrd"],
  [/\bthousand\b/gi, "tausn"],
  [/\bmillion\b/gi, "milyon"],
  [/\bhalf\b/gi, "haf"],

  // ── Negation / Affirmation ────────────────────────────────────────────
  [/\bnot\b/gi, "no"],
  [/\bno\b/gi, "nu"],
  [/\byes\b/gi, "yas"],
  [/\byeah\b/gi, "ye"],
  [/\byep\b/gi, "yap"],
  [/\bnah\b/gi, "na"],
  [/\bnope\b/gi, "nop"],
  [/\bok\b/gi, "oke"],
  [/\bokay\b/gi, "oke"],
  [/\boh\b/gi, "o"],
  [/\bah\b/gi, "a"],
  [/\buh\b/gi, "a"],
  [/\bwow\b/gi, "wau"],
  [/\booh\b/gi, "u"],
  [/\byo\b/gi, "yu"],

  // ── Seasons / Weather ─────────────────────────────────────────────────
  [/\bsummer\b/gi, "sama"],
  [/\bwinter\b/gi, "winta"],
  [/\bspring\b/gi, "sprin"],
  [/\bautumn\b/gi, "otam"],
  [/\bseason\b/gi, "sisn"],
  [/\bweather\b/gi, "weda"],
  [/\bclouds\b/gi, "klauds"],
  [/\bcloud\b/gi, "klaud"],
  [/\bthunder\b/gi, "tanda"],
  [/\blightning\b/gi, "laitnin"],
  [/\brainbow\b/gi, "renbo"],
  [/\bsunrise\b/gi, "sanrais"],
  [/\bsunset\b/gi, "sanse"],
  [/\bmidnight\b/gi, "midnai"],

  // ── Music / Performance ───────────────────────────────────────────────
  [/\bbeat\b/gi, "bit"],
  [/\bbeats\b/gi, "bits"],
  [/\brhythm\b/gi, "ridem"],
  [/\bmelody\b/gi, "melodi"],
  [/\bchorus\b/gi, "koras"],
  [/\bverse\b/gi, "vers"],
  [/\brap\b/gi, "rep"],
  [/\brapper\b/gi, "rapa"],
  [/\bband\b/gi, "ban"],
  [/\bstage\b/gi, "stej"],
  [/\bshow\b/gi, "sho"],
  [/\bconcert\b/gi, "konser"],
  [/\bparty\b/gi, "pari"],
  [/\bclub\b/gi, "klab"],

  // ── Misc common words ─────────────────────────────────────────────────
  [/\blittle\b/gi, "lito"],
  [/\bnotice\b/gi, "notis"],
  [/\bchance\b/gi, "chans"],
  [/\bchoice\b/gi, "choys"],
  [/\bnoise\b/gi, "noyz"],
  [/\bhorse\b/gi, "hos"],
  [/\bcourse\b/gi, "kos"],
  [/\bforce\b/gi, "fos"],
  [/\bonce\b/gi, "wans"],
  [/\btwice\b/gi, "twais"],
  [/\bpiece\b/gi, "pis"],
  [/\bstyle\b/gi, "stail"],
  [/\bcause\b/gi, "koz"],
  [/\bpause\b/gi, "poz"],
  [/\bspace\b/gi, "spes"],
  [/\bgrace\b/gi, "gres"],
  [/\bswing\b/gi, "swin"],
  [/\bstring\b/gi, "strin"],
  [/\bwing\b/gi, "win"],
  [/\bbelong\b/gi, "bilon"],
  [/\bsound\b/gi, "saun"],
  [/\bsounds\b/gi, "sauns"],
  [/\btown\b/gi, "taun"],
  [/\bpray\b/gi, "pre"],
  [/\bprayer\b/gi, "prea"],
  [/\bhaven\b/gi, "hafn"],
  [/\boften\b/gi, "ofn"],
  [/\bwild\b/gi, "waild"],
  [/\bkind\b/gi, "kaind"],
  [/\bblind\b/gi, "blaind"],
  [/\bsorry\b/gi, "sori"],
  [/\bworry\b/gi, "wori"],
  [/\bhurry\b/gi, "hari"],
  [/\bglory\b/gi, "glori"],
  [/\bhello\b/gi, "helo"],
  [/\bgoodbye\b/gi, "gudbai"],
  [/\bplease\b/gi, "plis"],
  [/\bthank\b/gi, "tank"],
  [/\bthanks\b/gi, "tanks"],
  [/\bscream\b/gi, "skrim"],
  [/\bstream\b/gi, "strim"],
  [/\bteam\b/gi, "tim"],
  [/\bmean\b/gi, "min"],
  [/\bmeans\b/gi, "mins"],
  [/\bmeaning\b/gi, "minin"],
  [/\bclean\b/gi, "klin"],
  [/\banother\b/gi, "anada"],
  [/\bwonder\b/gi, "wanda"],
  [/\bpower\b/gi, "pawa"],
  [/\btower\b/gi, "tawa"],
  [/\blonely\b/gi, "lonli"],
  [/\bhomely\b/gi, "homli"],
  [/\blovely\b/gi, "lufli"],
  [/\bsurely\b/gi, "shuli"],
  [/\bquickly\b/gi, "kwikli"],
  [/\bslowly\b/gi, "sloli"],
  [/\bhardly\b/gi, "hadli"],
  [/\bsoftly\b/gi, "sofli"],
  [/\bgently\b/gi, "jenli"],
  [/\bdeeply\b/gi, "dipli"],
  [/\bsimply\b/gi, "simpli"],
  [/\bclearly\b/gi, "kliali"],
  [/\bnearly\b/gi, "niali"],
  [/\bsecretly\b/gi, "sikreli"],
  [/\bperfectly\b/gi, "perfekli"],
  [/\bcompletely\b/gi, "komplitli"],
  [/\babsolutely\b/gi, "absoluli"],
  [/\bdefinitely\b/gi, "definetli"],
  [/\bhonestly\b/gi, "onesli"],
  [/\bnear\b/gi, "nia"],
  [/\bclear\b/gi, "klia"],
  [/\bdear\b/gi, "dia"],
  [/\bdeep\b/gi, "dip"],
  [/\bever\b/gi, "eva"],
  [/\blady\b/gi, "ledi"],

  // ── Feelings / States of Mind ─────────────────────────────────────────
  [/\balone\b/gi, "alon"],
  [/\bawake\b/gi, "awek"],
  [/\basleep\b/gi, "aslip"],
  [/\bafraid\b/gi, "afred"],
  [/\bscared\b/gi, "skead"],
  [/\bbored\b/gi, "bod"],
  [/\btired\b/gi, "taiad"],
  [/\bexcited\b/gi, "eksaid"],
  [/\bnervous\b/gi, "nervus"],
  [/\bjealous\b/gi, "jelus"],
  [/\bproud\b/gi, "praud"],
  [/\bashamed\b/gi, "ashemd"],
  [/\bguilty\b/gi, "gilti"],
  [/\bconfused\b/gi, "konfusd"],
  [/\blost\b/gi, "los"],
  [/\bstuck\b/gi, "stak"],
  [/\btrapped\b/gi, "trapd"],
  [/\bbroken\b/gi, "brokn"],
  [/\bhurt\b/gi, "her"],
  [/\bhurting\b/gi, "herin"],
  [/\bhealing\b/gi, "hilin"],
  [/\bwhole\b/gi, "hol"],
  [/\bempty\b/gi, "emti"],
  [/\bhungry\b/gi, "hangri"],
  [/\bthirsty\b/gi, "tersti"],
  [/\bsick\b/gi, "sik"],
  [/\bhealthy\b/gi, "helti"],
  [/\bweak\b/gi, "wik"],
  [/\bnumb\b/gi, "nam"],
  [/\bcruel\b/gi, "krul"],
  [/\bgentle\b/gi, "jento"],
  [/\bfierce\b/gi, "fias"],
  [/\bbrave\b/gi, "bref"],
  [/\bwicked\b/gi, "wikd"],
  [/\bholy\b/gi, "holi"],
  [/\bsacred\b/gi, "sekrd"],
  [/\bcursed\b/gi, "kersd"],
  [/\bblessed\b/gi, "blesd"],
  [/\bdesperate\b/gi, "despre"],
  [/\bhopeless\b/gi, "hoples"],
  [/\brestless\b/gi, "resles"],
  [/\breckless\b/gi, "rekles"],
  [/\bcareless\b/gi, "keles"],
  [/\bfearless\b/gi, "fiales"],
  [/\bheartless\b/gi, "hales"],
  [/\bmindless\b/gi, "mainles"],
  [/\bendless\b/gi, "enles"],
  [/\btimeless\b/gi, "taimles"],
  [/\bworthless\b/gi, "wotles"],
  [/\bpriceless\b/gi, "praisles"],
  [/\bfamous\b/gi, "femus"],
  [/\bdangerous\b/gi, "denjrus"],
  [/\bmysterious\b/gi, "mistirus"],
  [/\bserious\b/gi, "sirius"],
  [/\bprevious\b/gi, "privius"],
  [/\bobvious\b/gi, "obvius"],
  [/\bcurious\b/gi, "kyurius"],
  [/\bfurious\b/gi, "fyurius"],
  [/\bglorious\b/gi, "glorius"],
  [/\bprecious\b/gi, "preshus"],
  [/\bconscious\b/gi, "konshus"],
  [/\bnervous\b/gi, "nervus"],

  // ── More Action Verbs ─────────────────────────────────────────────────
  [/\bknock\b/gi, "nok"],
  [/\bknocking\b/gi, "nokin"],
  [/\bkicked\b/gi, "kikd"],
  [/\bkick\b/gi, "kik"],
  [/\bkicking\b/gi, "kikin"],
  [/\bjump\b/gi, "jamp"],
  [/\bjumping\b/gi, "jampin"],
  [/\bjumped\b/gi, "jampd"],
  [/\bswim\b/gi, "swem"],
  [/\bswimming\b/gi, "swimin"],
  [/\bswam\b/gi, "swem"],
  [/\bclimb\b/gi, "klaim"],
  [/\bclimbing\b/gi, "klaimin"],
  [/\bcrawl\b/gi, "krol"],
  [/\bcrawling\b/gi, "krolin"],
  [/\bslide\b/gi, "slaid"],
  [/\bsliding\b/gi, "slaidin"],
  [/\bslip\b/gi, "slep"],
  [/\bslipping\b/gi, "slipin"],
  [/\bslipped\b/gi, "slipd"],
  [/\bthrow\b/gi, "tro"],
  [/\bthrowing\b/gi, "troin"],
  [/\bthrew\b/gi, "tru"],
  [/\bthrown\b/gi, "tron"],
  [/\bcatch\b/gi, "kach"],
  [/\bcatching\b/gi, "kachin"],
  [/\bcaught\b/gi, "kot"],
  [/\bdrop\b/gi, "drap"],
  [/\bdropping\b/gi, "dropin"],
  [/\bdropped\b/gi, "dropd"],
  [/\bshoot\b/gi, "shu"],
  [/\bshooting\b/gi, "shuin"],
  [/\bshot\b/gi, "sho"],
  [/\bsteal\b/gi, "stil"],
  [/\bstealing\b/gi, "stilin"],
  [/\bstole\b/gi, "stol"],
  [/\bstolen\b/gi, "stoln"],
  [/\bhide\b/gi, "haid"],
  [/\bhiding\b/gi, "haidin"],
  [/\bhid\b/gi, "hed"],
  [/\bhidden\b/gi, "hidn"],
  [/\bseek\b/gi, "sik"],
  [/\bseeking\b/gi, "sikin"],
  [/\bsought\b/gi, "sot"],
  [/\bchase\b/gi, "ches"],
  [/\bchasing\b/gi, "chesin"],
  [/\bchased\b/gi, "chesd"],
  [/\bescape\b/gi, "eskep"],
  [/\bescaping\b/gi, "eskepin"],
  [/\bescaped\b/gi, "eskepd"],
  [/\bfight\b/gi, "fai"],
  [/\bfighting\b/gi, "faiin"],
  [/\bfought\b/gi, "fot"],
  [/\bwon\b/gi, "wan"],
  [/\bwinning\b/gi, "winin"],
  [/\bwin\b/gi, "wen"],
  [/\bbeat\b/gi, "bit"],
  [/\bbeating\b/gi, "bitin"],
  [/\btouch\b/gi, "tach"],
  [/\btouching\b/gi, "tachin"],
  [/\btouched\b/gi, "tachd"],
  [/\bkiss\b/gi, "kis"],
  [/\bkissing\b/gi, "kisin"],
  [/\bkissed\b/gi, "kisd"],
  [/\bhug\b/gi, "hag"],
  [/\bhugging\b/gi, "hagin"],
  [/\bhugged\b/gi, "hagd"],
  [/\bembrace\b/gi, "embres"],
  [/\bwrap\b/gi, "rap"],
  [/\bwrapping\b/gi, "rapin"],
  [/\bwrapped\b/gi, "rapd"],
  [/\bsqueeze\b/gi, "skwiz"],
  [/\bsqueezing\b/gi, "skwizin"],
  [/\bgrab\b/gi, "greb"],
  [/\bgrabbing\b/gi, "grabin"],
  [/\bgrabbed\b/gi, "grabd"],
  [/\bswear\b/gi, "swea"],
  [/\bswearing\b/gi, "sweain"],
  [/\bswore\b/gi, "swor"],
  [/\bsworn\b/gi, "swon"],
  [/\bpromise\b/gi, "promis"],
  [/\bpromising\b/gi, "promisin"],
  [/\bpromised\b/gi, "promisd"],
  [/\bbeg\b/gi, "bag"],
  [/\bbegging\b/gi, "begin"],
  [/\bbegged\b/gi, "begd"],
  [/\bbleed\b/gi, "blid"],
  [/\bbleeding\b/gi, "blidin"],
  [/\bbled\b/gi, "blad"],
  [/\bdrown\b/gi, "draun"],
  [/\bdrowning\b/gi, "draunin"],
  [/\bdrowned\b/gi, "draund"],
  [/\bsuffer\b/gi, "safa"],
  [/\bsuffering\b/gi, "safarin"],
  [/\bsuffered\b/gi, "safad"],
  [/\bstruggle\b/gi, "strago"],
  [/\bstruggling\b/gi, "stragolin"],
  [/\bsurvive\b/gi, "servaif"],
  [/\bsurviving\b/gi, "servaifin"],
  [/\bsurrender\b/gi, "sarenda"],
  [/\bsurrendering\b/gi, "sarendarin"],
  [/\bforgive\b/gi, "fogif"],
  [/\bforgiving\b/gi, "fogifin"],
  [/\bforgave\b/gi, "fogef"],
  [/\bforgiven\b/gi, "fogifn"],
  [/\bbetray\b/gi, "bitre"],
  [/\bbetrayed\b/gi, "bitred"],
  [/\bbetrayal\b/gi, "bitrel"],
  [/\btrust\b/gi, "tras"],
  [/\btrusting\b/gi, "trasin"],
  [/\btrusted\b/gi, "trasd"],
  [/\bdoubt\b/gi, "dau"],
  [/\bdoubting\b/gi, "dauin"],
  [/\bwonder\b/gi, "wanda"],
  [/\bwondering\b/gi, "wandarin"],
  [/\bwondered\b/gi, "wandad"],
  [/\bimagine\b/gi, "imajin"],
  [/\bimagining\b/gi, "imajinin"],
  [/\bimagined\b/gi, "imajind"],
  [/\bpretend\b/gi, "priten"],
  [/\bpretending\b/gi, "pritenin"],
  [/\bpretended\b/gi, "pritend"],
  [/\bexist\b/gi, "eksis"],
  [/\bexisting\b/gi, "eksisin"],
  [/\bexisted\b/gi, "eksisd"],
  [/\bbelong\b/gi, "bilon"],
  [/\bbelonging\b/gi, "bilonin"],
  [/\bbecome\b/gi, "bikam"],
  [/\bbecoming\b/gi, "bikamin"],
  [/\bbecame\b/gi, "bikem"],
  [/\bremain\b/gi, "rimen"],
  [/\bremaining\b/gi, "rimenin"],
  [/\bremained\b/gi, "rimend"],
  [/\brespect\b/gi, "rispek"],
  [/\bprotect\b/gi, "protek"],
  [/\bprotecting\b/gi, "protekin"],
  [/\bprotected\b/gi, "protekd"],
  [/\bdefend\b/gi, "difen"],
  [/\bdefending\b/gi, "difenin"],
  [/\battack\b/gi, "atak"],
  [/\battacking\b/gi, "atakin"],
  [/\bcontrol\b/gi, "kontrol"],
  [/\bcontrolling\b/gi, "kontrolin"],
  [/\brelease\b/gi, "rilis"],
  [/\breleasing\b/gi, "rilisin"],
  [/\breleased\b/gi, "rilisd"],

  // ── Communication / Expression ────────────────────────────────────────
  [/\bwhisper\b/gi, "wispa"],
  [/\bwhispering\b/gi, "wisparin"],
  [/\bwhispered\b/gi, "wispad"],
  [/\bshout\b/gi, "shau"],
  [/\bshouting\b/gi, "shauin"],
  [/\bshouted\b/gi, "shaud"],
  [/\byell\b/gi, "yel"],
  [/\byelling\b/gi, "yelin"],
  [/\byelled\b/gi, "yeld"],
  [/\bconfess\b/gi, "konfes"],
  [/\bconfessing\b/gi, "konfesin"],
  [/\bconfessed\b/gi, "konfesd"],
  [/\blie\b/gi, "la"],
  [/\blying\b/gi, "lain"],
  [/\blied\b/gi, "laid"],
  [/\bsilent\b/gi, "sailen"],
  [/\bsilence\b/gi, "sailens"],
  [/\bloud\b/gi, "lau"],
  [/\blouder\b/gi, "lauda"],
  [/\bloudest\b/gi, "laudes"],
  [/\banswer\b/gi, "ansa"],
  [/\banswering\b/gi, "ansarin"],
  [/\banswered\b/gi, "ansad"],
  [/\bquestion\b/gi, "kweshun"],
  [/\breply\b/gi, "ripla"],
  [/\brespond\b/gi, "rispon"],
  [/\bexplain\b/gi, "eksplen"],
  [/\bdescribe\b/gi, "diskriab"],
  [/\bexpress\b/gi, "ekspres"],
  [/\brepeat\b/gi, "ripit"],
  [/\brepeating\b/gi, "ripitin"],

  // ── Relationships / People ────────────────────────────────────────────
  [/\blover\b/gi, "luva"],
  [/\blovers\b/gi, "luvas"],
  [/\bpartner\b/gi, "patna"],
  [/\bhusband\b/gi, "hasban"],
  [/\bwife\b/gi, "waif"],
  [/\bfiance\b/gi, "fiansei"],
  [/\bboyfriend\b/gi, "bofren"],
  [/\bgirlfriend\b/gi, "galfren"],
  [/\bdarling\b/gi, "dalin"],
  [/\bhoney\b/gi, "hani"],
  [/\bsweetheart\b/gi, "switha"],
  [/\bneighbor\b/gi, "neba"],
  [/\bneighbour\b/gi, "neba"],
  [/\bstranger\b/gi, "strenja"],
  [/\benemy\b/gi, "enemi"],
  [/\benemies\b/gi, "enemis"],
  [/\bsoldier\b/gi, "solja"],
  [/\bsoldiers\b/gi, "soljas"],
  [/\bcaptain\b/gi, "kaptn"],
  [/\bgeneral\b/gi, "jenral"],
  [/\bdoctor\b/gi, "dokta"],
  [/\bteacher\b/gi, "ticha"],
  [/\bpreacher\b/gi, "pricha"],
  [/\bmaster\b/gi, "masta"],
  [/\bmister\b/gi, "mista"],
  [/\bsaint\b/gi, "sent"],
  [/\bsinner\b/gi, "sina"],
  [/\bkiller\b/gi, "kila"],
  [/\bsavior\b/gi, "sevia"],
  [/\bsaviour\b/gi, "sevia"],
  [/\bwinner\b/gi, "wina"],
  [/\bloser\b/gi, "lusa"],
  [/\bfighter\b/gi, "faita"],
  [/\bdancer\b/gi, "dansa"],
  [/\bsinger\b/gi, "singa"],
  [/\bplayer\b/gi, "plea"],
  [/\bdreamer\b/gi, "drima"],
  [/\bbeliever\b/gi, "biliva"],
  [/\bthief\b/gi, "tif"],
  [/\bthieves\b/gi, "tifs"],
  [/\bghost\b/gi, "gos"],
  [/\bghosts\b/gi, "goss"],
  [/\bspirit\b/gi, "spiri"],
  [/\bspirits\b/gi, "spiris"],
  [/\bmonster\b/gi, "monsta"],
  [/\bmonsters\b/gi, "monstas"],
  [/\bdemon\b/gi, "dimon"],
  [/\bdemons\b/gi, "dimons"],

  // ── Nature / Animals ──────────────────────────────────────────────────
  [/\bbird\b/gi, "bed"],
  [/\bbirds\b/gi, "beds"],
  [/\bwolf\b/gi, "wuf"],
  [/\bwolves\b/gi, "wufs"],
  [/\blion\b/gi, "laion"],
  [/\btiger\b/gi, "taiga"],
  [/\bbear\b/gi, "bea"],
  [/\bsnake\b/gi, "snek"],
  [/\bsnakes\b/gi, "sneks"],
  [/\bdragon\b/gi, "dragn"],
  [/\bdragons\b/gi, "dragns"],
  [/\bbutterfly\b/gi, "batafla"],
  [/\bbutterflies\b/gi, "bataflas"],
  [/\bcat\b/gi, "kat"],
  [/\bcats\b/gi, "kats"],
  [/\bdog\b/gi, "dag"],
  [/\bdogs\b/gi, "dags"],
  [/\bheart\b/gi, "har"],
  [/\bhearts\b/gi, "hars"],
  [/\bisland\b/gi, "ailan"],
  [/\bdesert\b/gi, "deser"],
  [/\bjungle\b/gi, "jango"],
  [/\bbeach\b/gi, "bich"],
  [/\bshore\b/gi, "sho"],
  [/\bcoast\b/gi, "kos"],
  [/\bvalley\b/gi, "vali"],
  [/\bhill\b/gi, "hil"],
  [/\bhills\b/gi, "hils"],
  [/\bcliff\b/gi, "klif"],
  [/\bcave\b/gi, "kef"],
  [/\brock\b/gi, "rok"],
  [/\brocks\b/gi, "roks"],
  [/\bstone\b/gi, "ston"],
  [/\bstones\b/gi, "stons"],
  [/\bdust\b/gi, "das"],
  [/\bdirt\b/gi, "der"],
  [/\bmud\b/gi, "mad"],
  [/\bsand\b/gi, "san"],
  [/\bgrass\b/gi, "gras"],
  [/\bseed\b/gi, "sid"],
  [/\bseeds\b/gi, "sids"],
  [/\broot\b/gi, "ru"],
  [/\broots\b/gi, "rus"],

  // ── Abstract / Conceptual ─────────────────────────────────────────────
  [/\btruth\b/gi, "trut"],
  [/\blies\b/gi, "las"],
  [/\bfaith\b/gi, "feit"],
  [/\bfate\b/gi, "fet"],
  [/\bdestiny\b/gi, "destni"],
  [/\bluck\b/gi, "lak"],
  [/\blucky\b/gi, "laki"],
  [/\bfortune\b/gi, "fochun"],
  [/\bmagic\b/gi, "majik"],
  [/\bmagical\b/gi, "majiko"],
  [/\bmiracle\b/gi, "mirako"],
  [/\bmystery\b/gi, "mistri"],
  [/\bwisdom\b/gi, "wizdom"],
  [/\bknowledge\b/gi, "nolej"],
  [/\blesson\b/gi, "lesn"],
  [/\blessons\b/gi, "lesns"],
  [/\bmistake\b/gi, "mistek"],
  [/\bmistakes\b/gi, "misteks"],
  [/\bregret\b/gi, "rigre"],
  [/\bregrets\b/gi, "rigres"],
  [/\bmemory\b/gi, "memri"],
  [/\bmemories\b/gi, "memris"],
  [/\bhistory\b/gi, "histri"],
  [/\bfuture\b/gi, "fyucha"],
  [/\bpast\b/gi, "pas"],
  [/\bpresent\b/gi, "presen"],
  [/\bmoment\b/gi, "momen"],
  [/\bforever\b/gi, "foreva"],
  [/\beternity\b/gi, "eterniti"],
  [/\binfinity\b/gi, "infiniti"],
  [/\breality\b/gi, "rialiti"],
  [/\bfantasy\b/gi, "fantsi"],
  [/\billusion\b/gi, "ilyushun"],
  [/\bshadow\b/gi, "shado"],
  [/\bshadows\b/gi, "shados"],
  [/\breflection\b/gi, "riflekshun"],
  [/\bmirror\b/gi, "mira"],
  [/\bglass\b/gi, "glas"],
  [/\bpicture\b/gi, "pikcha"],
  [/\bpictures\b/gi, "pikchas"],
  [/\bphoto\b/gi, "foto"],
  [/\bimage\b/gi, "imej"],
  [/\bvision\b/gi, "vishun"],
  [/\bvisions\b/gi, "vishuns"],
  [/\bcolor\b/gi, "kala"],
  [/\bcolour\b/gi, "kala"],
  [/\bcolors\b/gi, "kalas"],
  [/\bcolours\b/gi, "kalas"],
  [/\bbeauty\b/gi, "byuti"],
  [/\bsilver\b/gi, "silva"],
  [/\biron\b/gi, "aion"],
  [/\bsteel\b/gi, "stil"],

  // ── Clothing / Appearance ─────────────────────────────────────────────
  [/\bdress\b/gi, "dres"],
  [/\bdressed\b/gi, "dresd"],
  [/\bshirt\b/gi, "sher"],
  [/\bpants\b/gi, "pans"],
  [/\bjacket\b/gi, "jake"],
  [/\bcoat\b/gi, "kot"],
  [/\bhat\b/gi, "ha"],
  [/\bmask\b/gi, "mas"],
  [/\bmasked\b/gi, "masd"],
  [/\bnaked\b/gi, "nekd"],
  [/\bbare\b/gi, "bea"],
  [/\bwild\b/gi, "waild"],
  [/\bfaced\b/gi, "fesd"],
  [/\bscar\b/gi, "ska"],
  [/\bscars\b/gi, "skas"],
  [/\bwound\b/gi, "wun"],
  [/\bwounds\b/gi, "wuns"],
  [/\bwounded\b/gi, "wund"],
  [/\bmark\b/gi, "mak"],
  [/\bmarks\b/gi, "maks"],
  [/\bmarked\b/gi, "makd"],
  [/\bsign\b/gi, "sain"],
  [/\bsigns\b/gi, "sains"],
  [/\bsignal\b/gi, "signo"],

  // ── Actions / Physical ────────────────────────────────────────────────
  [/\bbreathe\b/gi, "brit"],
  [/\bbreathing\b/gi, "britin"],
  [/\bbreathed\b/gi, "britd"],
  [/\bswallow\b/gi, "swalo"],
  [/\bswallowing\b/gi, "swaloin"],
  [/\bbite\b/gi, "bai"],
  [/\bbiting\b/gi, "baitin"],
  [/\bbit\b/gi, "bi"],
  [/\bbitten\b/gi, "bitn"],
  [/\bspit\b/gi, "spi"],
  [/\bspitting\b/gi, "spiin"],
  [/\bchoke\b/gi, "chok"],
  [/\bchoking\b/gi, "chokin"],
  [/\bchoked\b/gi, "chokd"],
  [/\bshake\b/gi, "shek"],
  [/\bshaking\b/gi, "shekin"],
  [/\bshook\b/gi, "shuk"],
  [/\bshaken\b/gi, "shekn"],
  [/\btremble\b/gi, "trembo"],
  [/\btrembling\b/gi, "trembolin"],
  [/\bfreeze\b/gi, "friz"],
  [/\bfreezing\b/gi, "frizin"],
  [/\bfroze\b/gi, "fros"],
  [/\bfrozen\b/gi, "frosn"],
  [/\bmelt\b/gi, "mel"],
  [/\bmelting\b/gi, "melin"],
  [/\bmelted\b/gi, "meld"],
  [/\bpour\b/gi, "po"],
  [/\bpouring\b/gi, "poin"],
  [/\bpoured\b/gi, "pod"],
  [/\bspill\b/gi, "spil"],
  [/\bspilling\b/gi, "spilin"],
  [/\bspilled\b/gi, "spild"],
  [/\bsink\b/gi, "senk"],
  [/\bsinking\b/gi, "sinkin"],
  [/\bsank\b/gi, "senk"],
  [/\bsunk\b/gi, "sank"],
  [/\bfloat\b/gi, "flo"],
  [/\bfloating\b/gi, "floin"],
  [/\bspin\b/gi, "spen"],
  [/\bspinning\b/gi, "spinin"],
  [/\bspun\b/gi, "span"],
  [/\btwist\b/gi, "twis"],
  [/\btwisting\b/gi, "twisin"],
  [/\btwisted\b/gi, "twisd"],
  [/\bbend\b/gi, "ben"],
  [/\bbending\b/gi, "benin"],
  [/\bbent\b/gi, "ben"],
  [/\bstretch\b/gi, "strech"],
  [/\bstretching\b/gi, "strechin"],
  [/\breach\b/gi, "rich"],
  [/\breaching\b/gi, "richin"],
  [/\breached\b/gi, "richd"],
  [/\bpoint\b/gi, "poin"],
  [/\bpointing\b/gi, "poinin"],
  [/\bpointed\b/gi, "poind"],
  [/\bwipe\b/gi, "waip"],
  [/\bwiping\b/gi, "waipin"],
  [/\bwiped\b/gi, "waipd"],
  [/\bscratch\b/gi, "skrach"],
  [/\bscratching\b/gi, "skrachin"],

  // ── Places / Structure ────────────────────────────────────────────────
  [/\bcastle\b/gi, "kaso"],
  [/\bpalace\b/gi, "palas"],
  [/\btemple\b/gi, "tempo"],
  [/\btower\b/gi, "tawa"],
  [/\bbridge\b/gi, "brij"],
  [/\bgate\b/gi, "get"],
  [/\bgates\b/gi, "gets"],
  [/\bfence\b/gi, "fens"],
  [/\bpath\b/gi, "pat"],
  [/\bpaths\b/gi, "pats"],
  [/\btrail\b/gi, "trel"],
  [/\btrack\b/gi, "trak"],
  [/\bcorner\b/gi, "kona"],
  [/\bedge\b/gi, "ej"],
  [/\bborder\b/gi, "boda"],
  [/\blimit\b/gi, "limi"],
  [/\bbottom\b/gi, "botam"],
  [/\btop\b/gi, "tap"],
  [/\bcenter\b/gi, "senta"],
  [/\bcentre\b/gi, "senta"],
  [/\bmiddle\b/gi, "mido"],
  [/\bsurface\b/gi, "safes"],
  [/\bbeneath\b/gi, "binit"],
  [/\bhorizon\b/gi, "horisn"],
  [/\bsky\b/gi, "ska"],
  [/\bheaven\b/gi, "hefn"],
  [/\bhell\b/gi, "hel"],
  [/\bgrave\b/gi, "gref"],
  [/\bgraves\b/gi, "grefs"],
  [/\btomb\b/gi, "tum"],
  [/\bcross\b/gi, "kros"],
  [/\baltar\b/gi, "olta"],
  [/\bgarden\b/gi, "gadn"],
  [/\bparadise\b/gi, "paradais"],
  [/\bwonderland\b/gi, "wandalan"],
  [/\bkingdom\b/gi, "kingdam"],
  [/\bempire\b/gi, "empaia"],
  [/\bnation\b/gi, "neshun"],
  [/\bcountry\b/gi, "kantri"],

  // ── Objects / Things ──────────────────────────────────────────────────
  [/\bsword\b/gi, "sod"],
  [/\bswords\b/gi, "sods"],
  [/\bshield\b/gi, "shild"],
  [/\barmor\b/gi, "ama"],
  [/\barmour\b/gi, "ama"],
  [/\bweapon\b/gi, "wepn"],
  [/\bweapons\b/gi, "wepns"],
  [/\bbullet\b/gi, "bule"],
  [/\bbullets\b/gi, "bules"],
  [/\bbomb\b/gi, "bom"],
  [/\bbombs\b/gi, "boms"],
  [/\bknife\b/gi, "naif"],
  [/\bblade\b/gi, "bled"],
  [/\bblades\b/gi, "bleds"],
  [/\bcandle\b/gi, "kando"],
  [/\bcandles\b/gi, "kandos"],
  [/\btorch\b/gi, "toch"],
  [/\bflash\b/gi, "flas"],
  [/\bspark\b/gi, "spak"],
  [/\bsparks\b/gi, "spaks"],
  [/\bsmoke\b/gi, "smok"],
  [/\bash\b/gi, "as"],
  [/\bashes\b/gi, "ashs"],
  [/\bruins\b/gi, "ruens"],
  [/\bwreck\b/gi, "rek"],
  [/\bwreckage\b/gi, "rekej"],
  [/\btreasure\b/gi, "tresha"],
  [/\btreasures\b/gi, "treshas"],
  [/\bjewel\b/gi, "juel"],
  [/\bjewels\b/gi, "juels"],
  [/\bpearl\b/gi, "pel"],
  [/\bpearls\b/gi, "pels"],
  [/\bclock\b/gi, "klok"],
  [/\bwatch\b/gi, "woch"],
  [/\bbell\b/gi, "bel"],
  [/\bbells\b/gi, "bels"],
  [/\bkey\b/gi, "ki"],
  [/\bkeys\b/gi, "kis"],
  [/\block\b/gi, "lok"],
  [/\blocks\b/gi, "loks"],
  [/\blocked\b/gi, "lokd"],
  [/\bchain\b/gi, "chen"],
  [/\bchains\b/gi, "chens"],
  [/\brope\b/gi, "rop"],
  [/\bropes\b/gi, "rops"],
  [/\bwire\b/gi, "waia"],
  [/\bwires\b/gi, "waias"],
  [/\bstring\b/gi, "strin"],
  [/\bstrings\b/gi, "strins"],
  [/\bthread\b/gi, "tred"],
  [/\bneedle\b/gi, "nido"],
  [/\bcup\b/gi, "kap"],
  [/\bbottle\b/gi, "boto"],
  [/\bbottles\b/gi, "botos"],
  [/\bglass\b/gi, "glas"],
  [/\bglasses\b/gi, "glases"],
  [/\bmedicine\b/gi, "medisin"],
  [/\bpoison\b/gi, "poysn"],
  [/\bpill\b/gi, "pil"],
  [/\bpills\b/gi, "pils"],
  [/\bink\b/gi, "enk"],
  [/\bpaper\b/gi, "pepa"],
  [/\bpage\b/gi, "pej"],
  [/\bpages\b/gi, "pejs"],
  [/\bbook\b/gi, "buk"],
  [/\bbooks\b/gi, "buks"],
  [/\bmap\b/gi, "mep"],
  [/\bcompass\b/gi, "kampas"],
  [/\bflag\b/gi, "fleg"],
  [/\bflags\b/gi, "flegs"],
  [/\bwing\b/gi, "win"],
  [/\bwings\b/gi, "wins"],
  [/\bhalo\b/gi, "helo"],
  [/\bhorns\b/gi, "hons"],
  [/\bcage\b/gi, "kej"],
  [/\bcages\b/gi, "kejs"],
  [/\bprison\b/gi, "prisn"],
  [/\bjail\b/gi, "jel"],
  [/\btrap\b/gi, "trep"],
  [/\btraps\b/gi, "treps"],

  // ── Direction / Position ──────────────────────────────────────────────
  [/\bnorth\b/gi, "not"],
  [/\bsouth\b/gi, "sau"],
  [/\beast\b/gi, "is"],
  [/\bwest\b/gi, "wes"],
  [/\bleft\b/gi, "lef"],
  [/\bright\b/gi, "rai"],
  [/\bforward\b/gi, "fowad"],
  [/\bbackward\b/gi, "bakwad"],
  [/\bupward\b/gi, "apwad"],
  [/\bdownward\b/gi, "daunwad"],
  [/\babove\b/gi, "abuf"],
  [/\bbelow\b/gi, "bilo"],
  [/\bbeside\b/gi, "bisaid"],
  [/\btop\b/gi, "tap"],
  [/\bbottom\b/gi, "botam"],
  [/\bfront\b/gi, "fron"],
  [/\bbehind\b/gi, "bihaind"],
  [/\binside\b/gi, "insaid"],
  [/\boutside\b/gi, "autsaid"],
  [/\bcenter\b/gi, "senta"],

  // ── Food / Drink ──────────────────────────────────────────────────────
  [/\bfood\b/gi, "fud"],
  [/\bbread\b/gi, "bred"],
  [/\bwine\b/gi, "wain"],
  [/\bbeer\b/gi, "bia"],
  [/\bwhiskey\b/gi, "wiski"],
  [/\bwhisky\b/gi, "wiski"],
  [/\bdrink\b/gi, "drin"],
  [/\bdrinks\b/gi, "drins"],
  [/\bsweet\b/gi, "swit"],
  [/\bsweeter\b/gi, "swita"],
  [/\bsweetest\b/gi, "swites"],
  [/\bbitter\b/gi, "bita"],
  [/\bsour\b/gi, "saua"],
  [/\bsalt\b/gi, "sol"],
  [/\bsalty\b/gi, "solti"],
  [/\bsugar\b/gi, "shuga"],
  [/\bhoney\b/gi, "hani"],
  [/\bfruit\b/gi, "fru"],
  [/\bapple\b/gi, "apo"],
  [/\bcherry\b/gi, "cheri"],
  [/\brose\b/gi, "ros"],

  // ── Sizes / Amounts ───────────────────────────────────────────────────
  [/\bhuge\b/gi, "hyuj"],
  [/\btiny\b/gi, "taini"],
  [/\bwide\b/gi, "waid"],
  [/\bnarrow\b/gi, "naro"],
  [/\bthick\b/gi, "tik"],
  [/\bthin\b/gi, "tin"],
  [/\bheavy\b/gi, "hefi"],
  [/\blight\b/gi, "lai"],
  [/\blighter\b/gi, "laita"],
  [/\brightest\b/gi, "braites"],
  [/\bbrightest\b/gi, "braites"],
  [/\bbright\b/gi, "brai"],
  [/\bdim\b/gi, "dem"],
  [/\bfaint\b/gi, "fen"],
  [/\bsharp\b/gi, "shap"],
  [/\brough\b/gi, "raf"],
  [/\bsmooth\b/gi, "smu"],
  [/\bflat\b/gi, "fla"],
  [/\bround\b/gi, "raun"],
  [/\bstraight\b/gi, "stret"],
  [/\bcrooked\b/gi, "krukd"],

  // ── More common song words ────────────────────────────────────────────
  [/\bwanna\b/gi, "wana"],
  [/\bgonna\b/gi, "gona"],
  [/\bgotta\b/gi, "gota"],
  [/\bkinda\b/gi, "kainda"],
  [/\bsorta\b/gi, "soda"],
  [/\bdunno\b/gi, "dano"],
  [/\blemme\b/gi, "lemi"],
  [/\bgimme\b/gi, "gimi"],
  [/\bcmon\b/gi, "kmon"],
  [/\bimma\b/gi, "ima"],
  [/\btryna\b/gi, "traina"],
  [/\bfinna\b/gi, "fina"],
  [/\bwassup\b/gi, "wasap"],
  [/\bsuppose\b/gi, "sapos"],
  [/\bsupposed\b/gi, "saposd"],
  [/\bdifferent\b/gi, "difren"],
  [/\binteresting\b/gi, "intrestin"],
  [/\bimportant\b/gi, "impotan"],
  [/\bimpossible\b/gi, "imposibo"],
  [/\bincredible\b/gi, "inkredibo"],
  [/\bunbelievable\b/gi, "anbilifabo"],
  [/\bwonderful\b/gi, "wandafo"],
  [/\bamazing\b/gi, "amezin"],
  [/\bawesome\b/gi, "osom"],
  [/\bterrible\b/gi, "teribo"],
  [/\bhorrible\b/gi, "horibo"],
  [/\bpowerful\b/gi, "pawafo"],
  [/\bbeautiful\b/gi, "byutifo"],
  [/\bgrateful\b/gi, "grefo"],
  [/\bwatchful\b/gi, "wochfo"],
  [/\bfaithful\b/gi, "feitfo"],
  [/\bcheerful\b/gi, "chirfo"],
  [/\bpeaceful\b/gi, "pisfo"],
  [/\bplayful\b/gi, "plefo"],
  [/\bpainful\b/gi, "penfo"],
  [/\bharmful\b/gi, "hamfo"],
  [/\bhopeful\b/gi, "hopfo"],
  [/\bthankful\b/gi, "tankfo"],
  [/\btruthful\b/gi, "trutfo"],
  [/\bwasteful\b/gi, "westefo"],
  [/\bsinful\b/gi, "sinfo"],
  [/\bdreadful\b/gi, "dredfo"],
  [/\bawful\b/gi, "ofo"],
  [/\blawful\b/gi, "lofo"],
  [/\bunlawful\b/gi, "anlofo"],
  [/\bforgetful\b/gi, "fogefo"],
  [/\brespectful\b/gi, "rispekfo"],
  [/\bdisrespectful\b/gi, "disrispekfo"],
  [/\bregretful\b/gi, "rigrefo"],
  [/\bneglectful\b/gi, "niglekfo"],

  // ── Prefixed words ────────────────────────────────────────────────────
  [/\bunhappy\b/gi, "anhapi"],
  [/\bunkind\b/gi, "ankaind"],
  [/\bunfair\b/gi, "anfea"],
  [/\bunknown\b/gi, "annon"],
  [/\bunbroken\b/gi, "anbrokn"],
  [/\bunspoken\b/gi, "anspokn"],
  [/\bunforgiven\b/gi, "anfogifn"],
  [/\bunforgivable\b/gi, "anfogifabo"],
  [/\bunforgettable\b/gi, "anfogetabo"],
  [/\bunstoppable\b/gi, "anstopabo"],
  [/\bunbreakable\b/gi, "anbrekabo"],
  [/\bunbelievable\b/gi, "anbilifabo"],
  [/\bunconscious\b/gi, "ankonshus"],
  [/\bunaware\b/gi, "anawea"],
  [/\bunable\b/gi, "anebo"],
  [/\bunwanted\b/gi, "anwaned"],
  [/\bunloved\b/gi, "anlufd"],
  [/\buntouched\b/gi, "antachd"],
  [/\buntold\b/gi, "antold"],
  [/\bunreal\b/gi, "anril"],
  [/\bunfinished\b/gi, "anfinishd"],
  [/\buncertain\b/gi, "ansertn"],
  [/\breborn\b/gi, "ribon"],
  [/\bremade\b/gi, "rimed"],
  [/\breturn\b/gi, "riter"],
  [/\breturning\b/gi, "riterin"],
  [/\breturned\b/gi, "riterd"],
  [/\brevenge\b/gi, "rivenj"],
  [/\brebel\b/gi, "rebo"],
  [/\brefuse\b/gi, "rifyus"],
  [/\brefusing\b/gi, "rifyusin"],
  [/\brefused\b/gi, "rifyusd"],
  [/\breject\b/gi, "rijek"],
  [/\brejecting\b/gi, "rijekin"],
  [/\brejected\b/gi, "rijekd"],
  [/\bdisappear\b/gi, "disapia"],
  [/\bdisappearing\b/gi, "disapirin"],
  [/\bdisappeared\b/gi, "disapiad"],
  [/\bdiscover\b/gi, "diskova"],
  [/\bdiscovering\b/gi, "diskovarin"],
  [/\bdiscovered\b/gi, "diskovad"],
  [/\bdisguise\b/gi, "disgais"],
  [/\bdisguised\b/gi, "disgaisd"],
  [/\bdestruction\b/gi, "distrakshun"],
  [/\bconnect\b/gi, "konek"],
  [/\bconnecting\b/gi, "konekin"],
  [/\bconnected\b/gi, "konekd"],
  [/\bconnection\b/gi, "konekshun"],
  [/\bdisconnect\b/gi, "diskonek"],
  [/\bdisconnected\b/gi, "diskonekd"],

  // ── Weather / Atmospheric ─────────────────────────────────────────────
  [/\bfog\b/gi, "fag"],
  [/\bfoggy\b/gi, "fogi"],
  [/\bmist\b/gi, "mis"],
  [/\bmisty\b/gi, "misti"],
  [/\bhaze\b/gi, "hez"],
  [/\bhazy\b/gi, "hezi"],
  [/\bfrost\b/gi, "fros"],
  [/\bfrosty\b/gi, "frosti"],
  [/\bfreeze\b/gi, "friz"],
  [/\bfreezing\b/gi, "frizin"],
  [/\bburning\b/gi, "bernin"],
  [/\bboiling\b/gi, "boilin"],
  [/\bmelting\b/gi, "melin"],
  [/\bflooding\b/gi, "fladin"],
  [/\bflood\b/gi, "flad"],
  [/\bfloods\b/gi, "flads"],
  [/\bearthquake\b/gi, "ertwek"],
  [/\bvolcano\b/gi, "volkeno"],
  [/\bblizzard\b/gi, "blizad"],
  [/\bhurricane\b/gi, "hariken"],
  [/\btornado\b/gi, "tonedo"],
  [/\btyphoon\b/gi, "taifun"],
  [/\btsunami\b/gi, "sunami"],

  // ── Misc / Song-specific ────────────────────────────────────────────
  [/\bhey\b/gi, "he"],
  [/\bwoah\b/gi, "woa"],
  [/\bwhoa\b/gi, "woa"],
  [/\bda\b/gi, "de"],
  [/\bla\b/gi, "le"],
  [/\bive\b/gi, "aiv"],
  [/\bi've\b/gi, "aiv"],
  [/\bmr\b/gi, "mista"],
  [/\bmrs\b/gi, "misis"],

  // Fun / Slang
  [/\bfun\b/gi, "fan"],
  [/\bfunny\b/gi, "fani"],
  [/\bgreat\b/gi, "gre"],
  [/\bsuch\b/gi, "sach"],
  [/\bkinds\b/gi, "kains"],
  [/\bkind\b/gi, "kain"],
  [/\bmental\b/gi, "mentol"],
  [/\bchubby\b/gi, "chabi"],
  [/\bfiend\b/gi, "fin"],
  [/\bspeed\b/gi, "spid"],
  [/\bspeeding\b/gi, "spidin"],

  // -in' / -ing slang forms
  [/\bburnin\b/gi, "bernin"],
  [/\bburning\b/gi, "bernin"],
  [/\bhavin\b/gi, "hefin"],
  [/\bhaving\b/gi, "havin"],
  [/\bjumpin\b/gi, "jampin"],
  [/\bjumping\b/gi, "jampin"],
  [/\bshootin\b/gi, "shutin"],
  [/\bshooting\b/gi, "shutin"],
  [/\bstoppin\b/gi, "stopin"],
  [/\bstopping\b/gi, "stopin"],
  [/\bdisturbin\b/gi, "disterbin"],
  [/\bdisturbing\b/gi, "disterbin"],
  [/\btravelin\b/gi, "travalen"],
  [/\btraveling\b/gi, "travelin"],
  [/\btravelling\b/gi, "travelin"],
  [/\bcreatin\b/gi, "krieitin"],
  [/\bcreating\b/gi, "krieitin"],

  // Actions
  [/\bjoin\b/gi, "jon"],
  [/\bjoining\b/gi, "joinin"],
  [/\bjoined\b/gi, "joind"],
  [/\bimplode\b/gi, "implod"],
  [/\bimploding\b/gi, "implodin"],
  [/\bexplode\b/gi, "eksplod"],
  [/\bexploding\b/gi, "eksplodin"],
  [/\brequest\b/gi, "rikwes"],
  [/\brequesting\b/gi, "rikwesin"],

  // Body
  [/\bfoot\b/gi, "fut"],
  [/\bfeet\b/gi, "fit"],

  // Science / Abstract
  [/\batom\b/gi, "etom"],
  [/\batoms\b/gi, "etoms"],
  [/\bdegrees\b/gi, "digris"],
  [/\bdegree\b/gi, "digri"],
  [/\becstasy\b/gi, "ekstasi"],

  // Culture / Internet
  [/\bbritish\b/gi, "britis"],
  [/\btribes\b/gi, "traibs"],
  [/\btribe\b/gi, "traib"],
  [/\bworlds\b/gi, "werlds"],
  [/\bworld\b/gi, "werld"],
  [/\bworms\b/gi, "werms"],
  [/\bworm\b/gi, "werm"],
  [/\bportals\b/gi, "potals"],
  [/\bportal\b/gi, "potal"],
  [/\bmetaverse\b/gi, "metavers"],
  [/\bvrchat\b/gi, "viarchat"],
  [/\bali\b/gi, "eli"],
];

// ── Per-word phonetic rules (fallback for words NOT in dictionary) ─────
// Applied to each word BEFORE joining. Uses $ anchors and patterns
// that need word boundaries.
const PerWordPhoneticRules: [RegExp, string][] = [
  // Multi-char patterns
  [/ough/g, "o"],
  [/augh/g, "af"],
  [/ight/g, "ai"],
  [/ould/g, "u"],
  [/tion/g, "shun"],
  [/sion/g, "shun"],
  [/cious/g, "shus"],
  [/tious/g, "shus"],
  [/ious/g, "yus"],
  [/eous/g, "yus"],
  [/ture/g, "cha"],
  [/sure/g, "sha"],

  // Digraphs & silent combos
  [/wh/g, "w"],
  [/ck/g, "k"],
  [/ph/g, "f"],
  [/gh/g, ""],
  [/kn/g, "n"],
  [/wr/g, "r"],
  [/mb$/g, "m"],
  [/mn/g, "n"],

  // th → t
  [/th/g, "t"],

  // Ending patterns
  [/ness$/g, "nes"],
  [/ment$/g, "men"],
  [/able$/g, "abo"],
  [/ible$/g, "ibo"],
  [/ble$/g, "bo"],
  [/ple$/g, "po"],
  [/tle$/g, "to"],
  [/ful$/g, "fo"],
  [/ally$/g, "ali"],
  [/ously$/g, "usli"],
  [/ely$/g, "li"],
  [/ly$/g, "li"],
  [/ery$/g, "ri"],
  [/ary$/g, "ari"],
  [/ory$/g, "ori"],
  [/ity$/g, "iti"],
  [/ety$/g, "eti"],

  // -er, -or, -ar, -re endings → a
  [/ier$/g, "ia"],
  [/er$/g, "a"],
  [/or$/g, "a"],
  [/ar$/g, "a"],
  [/our$/g, "a"],
  [/re$/g, "a"],

  // -ed endings
  [/ied$/g, "id"],
  [/([aeiou])ted$/g, "$1d"],
  [/([aeiou])ded$/g, "$1d"],
  [/([^aeiou])ed$/g, "$1"],

  // -ing
  [/ing$/g, "in"],

  // Vowel digraphs — aggressively reduce
  [/eigh/g, "e"],
  [/ea/g, "e"],
  [/oo/g, "u"],
  [/ee/g, "i"],
  [/ie/g, "i"],
  [/ei/g, "e"],
  [/ou/g, "u"],
  [/oi/g, "oy"],
  [/au/g, "o"],
  [/aw/g, "o"],
  [/ow/g, "o"],
  [/ai/g, "e"],
  [/ay$/g, "e"],

  // Double consonants → single
  [/([bcdfghjklmnpqrstvwxyz])\1/g, "$1"],

  // Trailing silent 'e' after a consonant
  [/([bcdfghjklmnpqrstvwxyz])e$/g, "$1"],
];

/**
 * Palatalization — blends a trailing dental/alveolar plosive (t, d) with a
 * following word that starts with a /j/ sound (y + vowel).
 *
 *   t + y → ch   (e.g., "met you" → "mech" + "u" = "mechu")
 *   d + y → j    (e.g., "did you" → "dij" + "u" = "diju")
 *
 * Checks the ORIGINAL words to detect the blend, then modifies the
 * processed (gibberish) outputs accordingly.
 */
export function applyPalatalization(
  originalWords: string[],
  processedWords: string[],
): void {
  const debug = Defaults.DeveloperMode;

  for (let i = 0; i < originalWords.length - 1; i++) {
    const currentClean = originalWords[i].toLowerCase().replace(/[.,!?;:'"()\[\]{}\-—–…@#$%^&*~`]/g, "");
    const nextClean = originalWords[i + 1].toLowerCase().replace(/[.,!?;:'"()\[\]{}\-—–…@#$%^&*~`]/g, "");

    if (currentClean.length === 0 || nextClean.length === 0) continue;

    const lastChar = currentClean[currentClean.length - 1];
    const isAlveolar = lastChar === "t" || lastChar === "d";
    const nextStartsWithY = /^y[aeiou]/i.test(nextClean);

    if (isAlveolar && nextStartsWithY) {
      const blend = lastChar === "t" ? "ch" : "j";

      if (debug) {
        console.log(`[Wenomecha/Palatal] "${originalWords[i]}" + "${originalWords[i + 1]}" → ${lastChar}+y = ${blend} | "${processedWords[i]}" + "${processedWords[i + 1]}" → "${processedWords[i] + blend}" + "${processedWords[i + 1]}"`);
      }

      // Append the blend sound to the current word
      processedWords[i] = processedWords[i] + blend;
    }
  }
}

/**
 * Strip punctuation, spaces, and lowercase a word.
 */
function cleanWord(word: string): string {
  return word
    .toLowerCase()
    .replace(/[.,!?;:'"()\[\]{}\-—–…@#$%^&*~`\s]/g, "");
}

/**
 * Apply per-word phonetic mangling to a single word.
 * Only used for words NOT matched by the dictionary.
 */
function mangleWord(word: string): string {
  const debug = Defaults.DeveloperMode;
  let result = cleanWord(word);
  if (result.length === 0) return result;

  const before = result;
  for (const [pattern, replacement] of PerWordPhoneticRules) {
    const pre = result;
    result = result.replace(pattern, replacement);
    if (debug && result !== pre) {
      console.log(`[Wenomecha/Mangle]   Rule ${pattern} → "${replacement}" | "${pre}" → "${result}"`);
    }
  }
  if (debug && result === before) {
    console.log(`[Wenomecha/Mangle]   No phonetic rules matched for "${before}"`);
  }

  return result;
}

/**
 * Process a single sub-word (no hyphens): try dictionary first, fall back to phonetic mangling.
 * This prevents dictionary outputs from being double-mangled by phonetic rules.
 */
function processSubWord(word: string): { text: string; source: "dict" | "phonetic" } {
  const debug = Defaults.DeveloperMode;
  let result = word;
  let matched = false;
  const matchedPatterns: string[] = [];

  for (const [pattern, replacement] of WordReplacements) {
    // Reset lastIndex before test (global regexes are stateful)
    pattern.lastIndex = 0;
    if (pattern.test(result)) {
      matched = true;
      pattern.lastIndex = 0;
      result = result.replace(pattern, replacement);
      if (debug) matchedPatterns.push(`${pattern} → "${replacement}"`);
    }
  }

  if (matched) {
    const cleaned = cleanWord(result);
    if (debug) {
      console.log(`[Wenomecha/Word] "${word}" → "${cleaned}" (DICT: ${matchedPatterns.join(", ")})`);
    }
    return { text: cleaned, source: "dict" };
  }

  if (debug) {
    console.log(`[Wenomecha/Word] "${word}" → mangling (no dict match)`);
  }
  const cleaned = cleanWord(word);
  if (cleaned.length > 0) _missedWords.add(cleaned.toLowerCase());
  const mangled = mangleWord(word);
  if (debug) {
    console.log(`[Wenomecha/Word] "${word}" → "${mangled}" (PHONETIC)`);
  }
  return { text: mangled, source: "phonetic" };
}

/**
 * Process a word, splitting on hyphens/dashes so each part gets its own
 * dictionary lookup and phonetic pass.
 */
export function processWord(word: string): { text: string; source: "dict" | "phonetic" } {
  // Split on hyphens/dashes — each part is processed independently
  const parts = word.split(/[-—–]/);
  if (parts.length <= 1) {
    return processSubWord(word);
  }

  const debug = Defaults.DeveloperMode;
  if (debug) {
    console.log(`[Wenomecha/Word] Hyphenated: "${word}" → parts: ${parts.map((p) => `"${p}"`).join(", ")}`);
  }

  let anyDict = false;
  const processed = parts.map((part) => {
    const trimmed = part.trim();
    if (trimmed.length === 0) return { text: "", source: "phonetic" as const };
    const result = processSubWord(trimmed);
    if (result.source === "dict") anyDict = true;
    return result;
  });

  return {
    text: processed.map((p) => p.text).join(""),
    source: anyDict ? "dict" : "phonetic",
  };
}

/**
 * Transform a full line of lyrics into gibberish.
 * Each word is processed individually (dictionary first, then phonetic fallback),
 * then all words are joined together without spaces.
 *
 * Used for Line-synced and Static lyrics.
 */
export function gibberishifyLine(text: string): string {
  if (!text || text.trim().length === 0) return text;
  const debug = Defaults.DeveloperMode;

  if (debug) console.log(`[Wenomecha] ── INPUT: "${text}"`);

  const words = text.split(/\s+/);
  const processed = words.map((w) => processWord(w));
  const processedWords = processed.map((p) => p.text);

  // Palatalization: blend t/d + y across word boundaries
  applyPalatalization(words, processedWords);

  // Join words together (no spaces)
  let result = processedWords.join("");
  if (debug) console.log(`[Wenomecha] Joined: "${result}"`);

  // Final cleanup — collapse double consonants created by joining
  const beforeCleanup = result;
  result = result.replace(/([bcdfghjklmnpqrstvwxyz])\1/g, "$1");
  if (debug && result !== beforeCleanup) {
    console.log(`[Wenomecha] Cleanup: "${beforeCleanup}" → "${result}"`);
  }

  if (debug) {
    console.log(`[Wenomecha] ── OUTPUT: "${result}"`);
    console.log(`[Wenomecha] ── Word map: ${words.map((w, i) => `"${w}"→"${processedWords[i]}"`).join("  ")}`);
    console.log(`[Wenomecha] ──────────────────────────────────`);
  }

  return result;
}

